<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>.kos</string>
        <string>.craft</string>
    </array>
    <key>name</key>
    <string>k-OS</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>name</key>
            <string>text.source.kerboscript</string>
            <key>match</key>
            <string>\s*(?i:(set|log|rename))\s.*(?i:(to))\s*</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>text.source.kerboscript</string>
            <key>match</key>
            <string>\s*(?i:(copy))\s.*(?i:(to|from))\s*</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>text.source.kerboscript</string>
            <key>match</key>
            <string>\s*(?i:(delete))\s.*(?i:(from))\s*</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>text.source.kerboscript</string>
            <key>match</key>
            <string>\b(?i:(lock))\s.*(?i:(to))\b</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>text.source.kerboscript</string>
            <key>match</key>
            <string>\b(?i:(print))\s.+(?i:(at))\b</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>text.source.kerboscript</string>
            <key>match</key>
            <string>\b(?i:(when))\s.+(?i:(then))\b</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.kerboscript</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>keyword.source.kerboscript</string>
            <key>comment</key>
            <string>reserved word</string>
            <key>match</key>
            <string>\b(?i:add|remove|break|clearscreen|delete|declare( parameter)?|edit|print|remove|run|stage|switch to|toggle|unlock|until|wait|warp|reboot|shutdown|if|list|reboot)\b</string>
        </dict>
        <dict>
            <key>name</key>
            <string>keyword.source.kerboscript</string>
            <key>match</key>
            <string>\b(?i:sas|gear|rcs|lights|brakes|legs|chutes|panels) (on|off)\b</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>comment</key>
            <string>string</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.source.kerboscript</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>comment</string>
            <key>match</key>
            <string>//.*</string>
            <key>name</key>
            <string>comment.source.kerboscript</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.kerboscript</string>
    <key>uuid</key>
    <string>886bf29f-5844-4c49-8542-812a9e0ebc5c</string>
</dict>
</plist>
