<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>kOS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.source.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:add|print|remove|break|clearscreen|copy|delete|declare|edit|list|lock|on|log|rename|remove|run|set|stage|switch|toggle|unlock|reboot|shutdown)\s+[^\.]+$</string>
			<key>name</key>
			<string>invalid.illegal.source.kos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:heading|bearing|direction)\b</string>
			<key>name</key>
			<string>storage.type.source.kos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(?i:(set|log|rename))\s.*(?i:(to))\s*</string>
			<key>name</key>
			<string>text.source.kos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(?i:(copy))\s.*(?i:(to|from))\s*</string>
			<key>name</key>
			<string>text.source.kos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(?i:(delete))\s.*(?i:(from))\s*</string>
			<key>name</key>
			<string>text.source.kos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(lock))\s.*(?i:(to))\b</string>
			<key>name</key>
			<string>text.source.kos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.kos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(print))\s[^"]+(?i:(at))\b</string>
			<key>name</key>
			<string>text.source.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(when))\s.+(?i:(then))\b</string>
			<key>name</key>
			<string>text.source.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:add|remove|break|clearscreen|delete|declare( parameter)?|edit|print|remove|run|stage|switch to|toggle|unlock|warp|reboot|shutdown|list|reboot)\b</string>
			<key>name</key>
			<string>keyword.source.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:until|if|wait)\b</string>
			<key>name</key>
			<string>keyword.control.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:sas|gear|rcs|lights|brakes|legs|chutes|panels) (on|off)\b</string>
			<key>name</key>
			<string>support.function.source.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:abs|mod|floor|ceiling|round|round|sqrt|sin|cos|tan|arcsin|arccos|arctan|arctan2)\b</string>
			<key>name</key>
			<string>support.function.source.kos</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.source.kos</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kos</string>
	<key>uuid</key>
	<string>a73c33ac-e3fa-45c6-ba20-040413ac4dc4</string>
</dict>
</plist>
